FastMotors/FastMotors/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from FastMotorsApp import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^fastmotors/', include('FastMotorsApp.urls'))
]

FastMotors/FastMotorsApp/urls.py
from django.conf.urls import url
from . import views

app_name = 'FastMotorsApp'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^supervisor', views.supervisor, name='supervisor'),
    url(r'^security', views.security, name='security')
]

FastMotors/FastMotorsApp/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

# Create car models in the admin
class TruckModels(models.Model):
    model_name = models.CharField(max_length=200)

    def __str__(self):
        return self.model_name

# Create models for car part for service and their prices
class TruckParts(models.Model):
    part_no = models.CharField(max_length=200)
    description = models.CharField(max_length=300)
    service_price = models.PositiveIntegerField()
    model = models.ForeignKey(TruckModels, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.description } ({self.model}) ({self.service_price})'

class SecurityEntry(models.Model):
    driver_name = models.CharField(max_length=100)
    driver_phone = models.IntegerField()
    company_name = models.CharField(max_length=100)
    owner_name = models.CharField(max_length=100)
    owner_email = models.EmailField()
    truck_model = models.ForeignKey(TruckModels, on_delete=models.CASCADE)
    truck_registration = models.CharField(max_length=100)
    truck_chassis = models.IntegerField()
    engine_number = models.CharField(max_length=50)
    car_mileage = models.IntegerField()

    def __str__(self):
        return self.truck_registration

class SupervisorEntry(models.Model):
    truck_registration = models.ForeignKey(SecurityEntry, on_delete=models.CASCADE)
    truck_model = models.ForeignKey(TruckModels, on_delete=models.CASCADE)
    service_parts = models.TextField(max_length=1000)
    total_amount = models.IntegerField()

FastMotors/FastMotorsApp/forms.py
from django import forms
from .models import SecurityEntry, SupervisorEntry, TruckParts
from django.db.models import F


class SecurityEntryForm(forms.ModelForm):
    class Meta:
        model = SecurityEntry
        fields = '__all__'

class SupervisorEntryForm(forms.ModelForm):
    model_price = TruckParts.objects.filter(service_price=F('service_price'))
    service_type = forms.ModelMultipleChoiceField(widget=forms.CheckboxSelectMultiple, queryset=TruckParts.objects.filter(model= F("model")))
    class Meta:
        model = SupervisorEntry
        fields = ('truck_registration', 'truck_model', 'service_type', 'service_parts', 'total_amount')

FastMotors/FastMotorsApp/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db.models import F
from django.shortcuts import render
from  django.core.mail import send_mail
from .forms import SecurityEntryForm, SupervisorEntryForm
from .models import SupervisorEntry, SecurityEntry

# Create your views here.

# Index page
def index(request):

    return render(request, 'FastMotorsApp/index.html')

# Security Page
def security(request):
    security_form = SecurityEntryForm()
    if request.method == "POST":
        security_form= SecurityEntryForm(data=request.POST)
        #validate data enterd
        if security_form.is_valid():
            # Save data to the database if valid
            security_form.save(commit=True)
            # Send an email alert to the supervisor
            subject = "New Truck For Inspection"
            message = "The details are: \n" + security_form.cleaned_data['driver_name'] +' \n' + str(security_form.cleaned_data['truck_model']) + '\n' + security_form.cleaned_data['truck_registration']
            sender = 'security@fastmotors.co.ke'
            recipient = ['supervisor@fastmotors.co.ke']
            send_mail(subject, message, sender, recipient)
            return index(request)
    return render(request, "FastMotorsApp/security.html", {'security_form':security_form})

# Supervisor page
def supervisor(request):
    supervisor_form = SupervisorEntryForm()

    if request.method == 'POST':
        supervisor_form = SupervisorEntryForm(data=request.POST)
        # Checks if data entered is valid
        if supervisor_form.is_valid():
            # Saves data to the database.
            supervisor_form.save(commit=True)
            # Send Email to the owner
            subject = "Truck Inspection and The Estimated Price For Service"
            message = "Your truck {} has been recieved ant the estimated service price will be {}".format(supervisor_form.cleaned_data['truck_registration'], str(supervisor_form.cleaned_data['total_amount']))
            sender = 'supervisor@fastmotors.co.ke'
            recipient = [str(SecurityEntry.objects.filter(owner_email= F('owner_email')))]
            send_mail(subject, message, sender, recipient)
            return index(request)
    return render(request, 'FastMotorsApp/supervisor.html', {'supervisor_form':supervisor_form})

FastMotors/templates/FastMotorsApp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel='icon' href='{% static "images/favicon.ico" %}' type='image/x-icon'>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
    <link rel="stylesheet" href="{% static "css/main.css" %}">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light navbar-fixed-top bg-primary">
        <div class="navbar-header">
          <a href="{% url 'FastMotorsApp:index' %}" class="navbar-brand">FastMotors</a>
        </div>
        <button type="button" name="button" class="navbar-toggler bg-dark" data-toggle="collapse" data-target="#fastmotors" aria-controls="navbarSupportedContents" aria-expanded="false">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="fastmotors">
          <ul class="navbar-nav">
            <li class="nav-item"><a href="{% url 'FastMotorsApp:index' %}" class="nav-link">Home</a></li>
            <li class="nav-item"><a href="{% url 'FastMotorsApp:supervisor' %}" class="nav-link">Supervisor Entry</a></li>
            <li class="nav-item"><a href="{% url 'FastMotorsApp:security' %}" class="nav-link">Security Entry</a></li>
            <li class="nav-item"><a href="{% url 'admin:index' %}" class="nav-link">Admin</a></li>
          </ul>
        </div>
      </nav>
      <div class="container-fluid">
        {% block body_block%}
        {% endblock %}
      </div>
  </body>
</html>

FastMotors/templates/FastMotorsApp/index.html
<!DOCTYPE html>
{% extends "FastMotorsApp/base.html" %}
{% load static %}

{% block body_block %}
  <div class="welcome">
    <h1 class="display-4 text-center welcome-message">Welcom to FastMotors Stores</h1>
  </div>
{% endblock %}

FastMotors/templates/FastMotorsApp/security.html
<!DOCTYPE html >
{% extends "FastMotorsApp/base.html" %}
{% load static %}
{% block body_block%}
<div class="container">
  <div class="security">
    <h3 class="text-center security-message">Fill In The Truck Details</h3>
  </div>
  <div class="container">
    <form method="POST" class="form">
        <table class="table table-stripped">
           {{ security_form.as_table }}
            {% csrf_token %}
        </table>
        <div class="input-group">
          <input type="submit" value="Save Data And Send Email" class="btn btn-primary">
        </div>
    </form>
  </div>
</div>
{% endblock %}

FastMotors/templates/FastMotorsApp/supervisor.html
<!DOCTYPE html>
{% extends "FastMotorsApp/base.html"%}
{% load static %}
{% block body_block%}
    <div class="container">
      <div class="supervisor text-center">
        <h3>Fill In The Details</h3>
      </div>

<script>

    $(document).ready(function() {

        $(".btn").click(function(){

            var services = [];

            $.each($("input[name='service_type']:checked"), function(){

                $("textarea").append(services.push($(this).val()));

            });
        });

    });

    $(document).ready(function(){
      $("textarea").hide();
    });

</script>
      <div class="container">
        <form method="POST" class="form">
            <table class="table">
                {{ supervisor_form.as_table}}
                {% csrf_token %}
            </table>
            <input type="submit", value="Save Data" class="btn btn-primary">
        </form>
      </div>
    </div>
{% endblock %}